import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
import { SignOutButton, useUser } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div> Loading... </div>;
  if (!data) return <div> Something went wrong</div>;

  const CreatePostWizard = () => {
    const { user } = useUser();
    if (!user) return null;
    return (
      <div className=" flex gap-4 w-full ">
        <img
          src={user.imageUrl}
          alt="Github pfp"
          className="h-12 w-12 rounded-full"
        />
        <input placeholder="Post some pigs" className=" bg-transparent grow outline-none" />
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Emo Ponj</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center  ">
        <div className="h-full w-full border-x border-slate-200 bg-slate-200 md:max-w-2xl">
          <div className="flex  border-b border-slate-200 p-8">
            {" "}
            {!user.isSignedIn && <SignIn />}
            {user.isSignedIn && <CreatePostWizard />}
          </div>

          <div className="flex flex-col">
            {data?.map((post) => (
              <div key={post.id} className="border-b border-slate-300 p-8">
                {post.content}
              </div>
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
