import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";
import { number } from "zod";
import relativeTime from "dayjs/plugin/relativeTime";
import dayjs from "dayjs";
import { LoadingPage } from "~/components/loading";
dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();
  if (!user) return null;
  return (
    <div className=" flex w-full gap-4 ">
      <Image
        src={user.imageUrl}
        alt={`@${user.username} Github"`}
        className=" rounded-full"
        width={56}
        height={56}
      />
      <input
        placeholder="Post some pigs"
        className=" grow bg-transparent outline-none"
      />
    </div>
  );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = (props: PostWithUser) => {
  const { post, author } = props;
  return (
    <div key={post.id} className="flex gap-5 border-b border-slate-300  p-8 ">
      <Image
        src={author.imageUrl}
        alt={`@${author.username} Github pfp"`}
        className="rounded-full"
        width={50}
        height={50}
      />
      <div className="flex flex-col">
        <div className=" flex  gap-3">
          <span className=" text-slate-200">{`@${author.username}`}</span>
          <span className=" text-slate-500">{`${dayjs(post.createdAt).fromNow()}`}</span>
        </div>
        <span className=" text-slate-50">{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.post.getAll.useQuery();
  
  if (postsLoading) return <LoadingPage size={40}/>;
  if (!data) return <div> Something went wrong</div>;
  return(
  <div className="flex flex-col">
    {data?.map((fullPost) => <PostView {...fullPost} key={fullPost.post.id} />)}
  </div>);
};

export default function Home() {
  const {isLoaded: userLoaded, isSignedIn} = useUser();
  
  if (!userLoaded) return <LoadingPage size={56}/>;

  return (
    <>
      <Head>
        <title>Emo Ponj</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center  ">
        <div className="h-full w-full border-x border-slate-200 bg-slate-200 md:max-w-2xl">
          <div className="flex  border-b border-slate-200 p-8">
            {" "}
            {!isSignedIn && <SignIn />}
            {isSignedIn && <CreatePostWizard />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
