import Head from "next/head";
import Image from "next/image";
import { api } from "~/utils/api";
import type { RouterOutputs } from "~/utils/api";
import { useUser } from "@clerk/nextjs";
import { SignIn } from "@clerk/nextjs";
import { number } from "zod";
import relativeTime from "dayjs/plugin/relativeTime";
import dayjs from "dayjs";
dayjs.extend(relativeTime);

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();

  if (isLoading) return <div> Loading... </div>;
  if (!data) return <div> Something went wrong</div>;

  const CreatePostWizard = () => {
    const { user } = useUser();
    if (!user) return null;
    return (
      <div className=" flex w-full gap-4 ">
        <Image
          src={user.imageUrl}
          alt={`@${user.username} Github"`}
          className=" rounded-full"
          width={56}
          height={56}
        />
        <input
          placeholder="Post some pigs"
          className=" grow bg-transparent outline-none"
        />
      </div>
    );
  };

  type PostWithUser = RouterOutputs["post"]["getAll"][number];
  const PostView = (props: PostWithUser) => {
    const { post, author } = props;
    return (
      <div key={post.id} className="flex gap-5 border-b border-slate-300  p-8 ">
        <Image
          src={author.imageUrl}
          alt={`@${author.username} Github pfp"`}
          className="rounded-full"
          width={50}
          height={50}
        />
        <div className="flex flex-col">
          <div className="flex-slate-300 flex  gap-3">
            <span>{`@${author.username}`}</span>
            <span>{`${dayjs(post.createdAt).fromNow()}`}</span>
          </div>
          <span>{post.content}</span>
        </div>
      </div>
    );
  };

  return (
    <>
      <Head>
        <title>Emo Ponj</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex min-h-screen flex-col items-center  ">
        <div className="h-full w-full border-x border-slate-200 bg-slate-200 md:max-w-2xl">
          <div className="flex  border-b border-slate-200 p-8">
            {" "}
            {!user.isSignedIn && <SignIn />}
            {user.isSignedIn && <CreatePostWizard />}
          </div>

          <div className="flex flex-col">
            {data?.map((fullPost) => (
              <PostView {...fullPost} key={fullPost.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
